
package main;

import d.dashboard;
import config.DBC;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.sql.*;


public class panel extends javax.swing.JFrame {

    /**
     * Creates new form panel
     */
    public panel() {
        initComponents();
        
        // 1. Setup the initial look
    username.setText("Enter Username...");
    

    // 2. Add the Listener
    username.addFocusListener(new FocusListener() {
        @Override
        public void focusGained(FocusEvent e) {
            // IF text is the placeholder, clear it
            if (username.getText().equals("Enter Username...")) {
                username.setText("");
              
            }
        }

        @Override
        public void focusLost(FocusEvent e) {
            // IF user didn't type anything, put the placeholder back
            if (username.getText().isEmpty()) {
                username.setText("Enter Username...");
               
            }
        }

   
    });
    String pass = String.valueOf(password.getPassword());


    setSize(750, 500); 
    
    // 2. Center it
    setLocationRelativeTo(null);
    
    password.setEchoChar((char)0); // Make visible
password.setText("Enter Password");
password.setForeground(new java.awt.Color(153, 153, 153)); // Gray

// 2. Add the listener manually
password.addFocusListener(new java.awt.event.FocusAdapter() {
    
    // WHEN CLICKED
    public void focusGained(java.awt.event.FocusEvent evt) {
        String pass = String.valueOf(password.getPassword());
        if (pass.equals("Enter Password")) {
            password.setText("");
            password.setForeground(java.awt.Color.BLACK);
            password.setEchoChar('*'); // Hide password
        }
    }

    // WHEN LEFT
    public void focusLost(java.awt.event.FocusEvent evt) {
        String pass = String.valueOf(password.getPassword());
        if (pass.length() == 0 || pass.equals("")) {
            password.setText("Enter Password");
            password.setForeground(new java.awt.Color(153, 153, 153));
            password.setEchoChar((char)0); // Show text
        }
    }
});
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setLabelFor(this);
        jLabel1.setText("Bike shop");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, 40));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 770, 70);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        username.setText("Enter name");
        username.setDragEnabled(true);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 200, 30));

        password.setText("jPasswordField1");
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 200, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("log in");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jLabel2MouseWheelMoved(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 34, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("register");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 50, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("welcome too bike shop");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 380, 110));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 770, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jLabel2MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jLabel2MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseWheelMoved

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

  

// 2. DEFINE A VARIABLE TO TRACK ERRORS
boolean hasError = false;

// 3. CHECK USERNAME
// If username is empty OR equals the placeholder text
if (username.equals("") || username.equals("Enter Username...")) {
    username.setVisible(true); // Show Red *
    username.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED)); // Red Border
    hasError = true;
} else {
    username.setVisible(false); // Hide Red *
    username.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY)); // Reset Border
}

// 4. CHECK PASSWORD
if (password.equals("") || password.equals("Enter Password")) {
    password.setVisible(true); // Show Red *
    password.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED)); // Red Border
    hasError = true;
} else {
    password.setVisible(false); // Hide Red *
    password.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY)); // Reset Border
}

// 5. PROCEED ONLY IF NO ERRORS
if (hasError == false) {
    // --- YOUR SUCCESS CODE GOES HERE ---
    
    // Check credentials (Optional)
    // if (username.equals("admin") && password.equals("123")) {
        
       loading load = new loading("page");
        load.setVisible(true);
        this.dispose();
        
    // } else {
    //    javax.swing.JOptionPane.showMessageDialog(this, "Wrong Account!");
    // }
}
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
         loading load = new loading("landng");
        load.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
    
       String user = username.getText();
    String rawPass = String.valueOf(password.getText());
    
    // 2. CHECK EMPTY FIELDS
    if(user.isEmpty() || rawPass.isEmpty() || user.equals("Enter Username...")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.");
        return;
    }

    try {
        // 3. CONNECT TO DATABASE
        // Use your specific connection string here
       DBC con = new DBC();  
        
        // 4. CHECK USER
        String sql = "SELECT password, role FROM Tbl_user WHERE username = ?";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, user);
        
        java.sql.ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            String dbPass = rs.getString("password"); // Hashed password from DB
            String dbRole = rs.getString("role");     // 'Admin' or 'User'

            // 5. HASH THE INPUT PASSWORD
            // Make sure you have the PasswordUtil class we created earlier
            String inputHash = password.getText();

            // 6. COMPARE
            if (inputHash.equals(dbPass)) {
                
                // --- SUCCESS ---
                this.dispose(); // Close Login Window
                
                // Open Loading Screen
                loading loadScreen = new loading();
                loadScreen.setVisible(true);

                // --- TIMER (3 Seconds Delay) ---
                javax.swing.Timer timer = new javax.swing.Timer(3000, new java.awt.event.ActionListener() {
                    @Override
                    public void actionPerformed(java.awt.event.ActionEvent e) {
                        loadScreen.dispose(); // Close loading
                        
                        // Check Role and Open Dashboard
                        if (dbRole.equalsIgnoreCase("Admin")) {
                            new dashboard().setVisible(true);
                        } else {
                            new dashboard().setVisible(true);
                        }
                    }
                });
                timer.setRepeats(false);
                timer.start();

            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Incorrect Password");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Username not found");
        }
        con.close();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jPanel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
