
package main;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.sql.*;


public class panel extends javax.swing.JFrame {

    /**
     * Creates new form panel
     */
    public panel() {
        initComponents();
        
        // 1. Setup the initial look
    jTextField1.setText("Enter Username...");
    

    // 2. Add the Listener
    jTextField1.addFocusListener(new FocusListener() {
        @Override
        public void focusGained(FocusEvent e) {
            // IF text is the placeholder, clear it
            if (jTextField1.getText().equals("Enter Username...")) {
                jTextField1.setText("");
              
            }
        }

        @Override
        public void focusLost(FocusEvent e) {
            // IF user didn't type anything, put the placeholder back
            if (jTextField1.getText().isEmpty()) {
                jTextField1.setText("Enter Username...");
               
            }
        }

   
    });
    String pass = String.valueOf(jPasswordField1.getPassword());


    setSize(750, 500); 
    
    // 2. Center it
    setLocationRelativeTo(null);
    
    jPasswordField1.setEchoChar((char)0); // Make visible
jPasswordField1.setText("Enter Password");
jPasswordField1.setForeground(new java.awt.Color(153, 153, 153)); // Gray

// 2. Add the listener manually
jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
    
    // WHEN CLICKED
    public void focusGained(java.awt.event.FocusEvent evt) {
        String pass = String.valueOf(jPasswordField1.getPassword());
        if (pass.equals("Enter Password")) {
            jPasswordField1.setText("");
            jPasswordField1.setForeground(java.awt.Color.BLACK);
            jPasswordField1.setEchoChar('*'); // Hide password
        }
    }

    // WHEN LEFT
    public void focusLost(java.awt.event.FocusEvent evt) {
        String pass = String.valueOf(jPasswordField1.getPassword());
        if (pass.length() == 0 || pass.equals("")) {
            jPasswordField1.setText("Enter Password");
            jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
            jPasswordField1.setEchoChar((char)0); // Show text
        }
    }
});
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setLabelFor(this);
        jLabel1.setText("Bike shop");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 770, 70);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField1.setText("Enter name");
        jTextField1.setDragEnabled(true);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 200, 30));

        jPasswordField1.setText("jPasswordField1");
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 200, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("log in");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jLabel2MouseWheelMoved(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 34, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("register");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 50, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("welcome too bike shop");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 380, 110));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 770, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel2MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jLabel2MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseWheelMoved

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

  
String username = jTextField1.getText();
String password = String.valueOf(jPasswordField1.getPassword());

// 2. DEFINE A VARIABLE TO TRACK ERRORS
boolean hasError = false;

// 3. CHECK USERNAME
// If username is empty OR equals the placeholder text
if (username.equals("") || username.equals("Enter Username...")) {
    jTextField1.setVisible(true); // Show Red *
    jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED)); // Red Border
    hasError = true;
} else {
    jTextField1.setVisible(false); // Hide Red *
    jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY)); // Reset Border
}

// 4. CHECK PASSWORD
if (password.equals("") || password.equals("Enter Password")) {
    jPasswordField1.setVisible(true); // Show Red *
    jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED)); // Red Border
    hasError = true;
} else {
    jPasswordField1.setVisible(false); // Hide Red *
    jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY)); // Reset Border
}

// 5. PROCEED ONLY IF NO ERRORS
if (hasError == false) {
    // --- YOUR SUCCESS CODE GOES HERE ---
    
    // Check credentials (Optional)
    // if (username.equals("admin") && password.equals("123")) {
        
       loading load = new loading("page");
        load.setVisible(true);
        this.dispose();
        
    // } else {
    //    javax.swing.JOptionPane.showMessageDialog(this, "Wrong Account!");
    // }
}
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
         loading load = new loading("landng");
        load.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
